// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Q1QS_31tmu76Kgj_1EwgDK-JSns_fBg',
    appId: '1:393062738879:web:e8c51aeb2771135c6b4f0a',
    messagingSenderId: '393062738879',
    projectId: 'test-9e3f7',
    authDomain: 'test-9e3f7.firebaseapp.com',
    storageBucket: 'test-9e3f7.appspot.com',
    measurementId: 'G-M4GDD7X556',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Pbj1wU3tHFrsXoaEok43qFzk0Iv1yVs',
    appId: '1:393062738879:android:4de83a089fba6db86b4f0a',
    messagingSenderId: '393062738879',
    projectId: 'test-9e3f7',
    storageBucket: 'test-9e3f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgXdmka8RxmYFEr7Om74HhXZX7gDstn3g',
    appId: '1:393062738879:ios:0cdf200c68363b046b4f0a',
    messagingSenderId: '393062738879',
    projectId: 'test-9e3f7',
    storageBucket: 'test-9e3f7.appspot.com',
    iosBundleId: 'com.example.firebaseDatabase01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgXdmka8RxmYFEr7Om74HhXZX7gDstn3g',
    appId: '1:393062738879:ios:0cdf200c68363b046b4f0a',
    messagingSenderId: '393062738879',
    projectId: 'test-9e3f7',
    storageBucket: 'test-9e3f7.appspot.com',
    iosBundleId: 'com.example.firebaseDatabase01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Q1QS_31tmu76Kgj_1EwgDK-JSns_fBg',
    appId: '1:393062738879:web:403c90468c3d1ded6b4f0a',
    messagingSenderId: '393062738879',
    projectId: 'test-9e3f7',
    authDomain: 'test-9e3f7.firebaseapp.com',
    storageBucket: 'test-9e3f7.appspot.com',
    measurementId: 'G-26HFN923QW',
  );
}
